### ISSUE TITLE
[advice/help] Counting junction usage from BAM file

### ISSUE THREAD

**Issue by nickhsmith** [LieberInstitute/megadepth#1]
Hello everyone, I am interested in aberrant splicing events and as a result, I am trying to count reads and the junctions that they support without an annotation file so I can detect new splice junctions or exon elongations.

My question is megadepth seems like a fast R option for counting, but the documentation I've seen requires annotation files. I've played around with `bam_to_junctions("example.bam")` but I was really hoping for a way to pileup this information. For example I get a table that looks like this (after using `read_junction_table`)

 example_jxs <- read_junction_table(example_bam_junctions)
> example_jxs
A tibble: 19,204,791 x 7
   read_name chr   start   end mapping_strand cigar      unique
       <dbl> <chr> <dbl> <dbl> <chr>          <chr>       <int>
 1        17 1     12228 12612 +              43M385N33M      0
 2         4 1     12228 12612 -              29M385N47M      0
 3        19 1     12228 12594 +              18M367N58M      0
 4        24 1     12228 12612 +              10M385N66M      0
 5         9 1     12228 12594 +              8M367N68M       0
 6         5 1     12228 12612 +              4M385N72M       0
 7         9 1     12722 13220 -              73M499N3M       0
 8        18 1     12698 13402 +              30M705N46M      0
 9        10 1     12722 13402 -              53M681N23M      0
10        21 1     12722 13402 +              50M681N26M      0
… with 19,204,781 more rows

And I notice that rows 1,2,4,6 all support the same junction. I was hoping there was an easy way to pile up this information into a count vector for each junction. Before I spent the time and effort to write an overlapping/counting function I figured I would ask the experts. 

In this toy example (first 10 rows) I would get:
chr  | start | end | count
----- | ------ | ----- | -------
1 | 12228 | 12612 | 4
1 | 12228 | 12594 | 2
1 | 12722 | 13220 | 1
1 | 12698 | 13402 | 1 
1 | 12722 | 13402 | 2

Thanks in advance

**Comment by dzhang32** [comment]
Hi,

This junction format issue looks to be addressed in the original [Megadepth](https://github.com/ChristopherWilks/megadepth#junctions) through a helper script found here: https://github.com/ChristopherWilks/megadepth/blob/master/junctions/process_jx_output.sh. Currently, this is not yet part of the R package - the `reprex` below shows how you could use this to process the output of `read_junction_table()`. 

Hope this helps! Working a lot with splicing myself, I'd also find the processed junction format much more useful and I'll discuss with the Megadepth authors about incorporating this helper script as part of the R package. 

Best, 

David 

``` r
library(tidyverse)
library(megadepth)

example_bam <- system.file("tests",
                           "test2.bam",
                           package = "megadepth",
                           mustWork = TRUE
)

example_jxs <- bam_to_junctions(example_bam, overwrite = TRUE)
all_jxs <- read_junction_table(example_jxs[["all_jxs.tsv"]])

# raw junctions
all_jxs
#> # A tibble: 7 x 7
#>   read_name chr     start     end mapping_strand cigar                unique
#>       <dbl> <chr>   <dbl>   <dbl> <chr>          <chr>                 <int>
#> 1   7504219 chr1    18310  188572 +              36M170263N12M206N27M      1
#> 2   7504219 chr1   188585  188790 +              36M170263N12M206N27M      1
#> 3  19540155 chr10 4195113 4519182 +              10M324070N62M             0
#> 4  19905142 chr10 4195113 4519182 +              10M324070N62M             0
#> 5  27213900 chr10 4195113 4519182 +              10M324070N62M             0
#> 6  19540155 chr10 4246673 4519182 -              10M272510N62M             0
#> 7  19905142 chr10 4246673 4519182 -              10M272510N62M             0

# process using process_jx_output.sh
all_jxs %>% write_delim(file.path(tempdir(), "all_jxs.tsv"), delim = "\t")

download.file("https://raw.githubusercontent.com/ChristopherWilks/megadepth/master/junctions/process_jx_output.sh", 
              file.path(tempdir(), "process_jx_output.sh"))

system(paste(
  "source",
  file.path(tempdir(), "process_jx_output.sh"), 
  file.path(tempdir(), "all_jxs.tsv")
))

# processed junctions
read_delim(file.path(tempdir(), "all_jxs.tsv.sjout"), delim = "\t")
#> Warning: Missing column names filled in: 'X9' [9]
#> Warning: Duplicated column names deduplicated: '0' => '0_1' [5], '0' =>
#> '0_2' [6], '0' => '0_3' [7]
#> 
#> ── Column specification ────────────────────────────────────────────────────────
#> cols(
#>   chr = col_character(),
#>   start = col_double(),
#>   end = col_double(),
#>   `0` = col_double(),
#>   `0_1` = col_double(),
#>   `0_2` = col_double(),
#>   `0_3` = col_double(),
#>   `1` = col_double(),
#>   X9 = col_logical()
#> )
#> # A tibble: 4 x 9
#>   chr     start     end   `0` `0_1` `0_2` `0_3`   `1` X9   
#>   <chr>   <dbl>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <lgl>
#> 1 chr1    18310  188572     0     0     0     1     0 NA   
#> 2 chr1   188585  188790     0     0     0     1     0 NA   
#> 3 chr10 4195113 4519182     0     0     0     0     3 NA   
#> 4 chr10 4246673 4519182     0     0     0     0     2 NA
```

<sup>Created on 2021-04-20 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by lcolladotor** [comment]
Hi @nickhsmith,

We are thinking of porting that bash script into an R function. Thanks for creating this issue!

We'll use this issue to track our progress.

Best,
Leo

**Comment by nickhsmith** [comment]
Thanks for the update, and for the advice! Another question I have is about BAM mapping ambiguity.

I was looking at a read that has an equivalent mapping score to two different parts of the genome. I was wondering if there is an ambiguous counting where if read 1 matches to a position A in the genome and also to position B in the genome with equivalent mapping scores, that I can count this read for both positions. Because I'm interested in rare splicing, I'm happy to double count this for both positions A and B because if one of them is new, or interesting in some way it's worth it for me.

Currently, it seems like the functionality is that it only counts the ambiguous read for one of the positions (I'm not sure why it choose A over B, or B over A). Is there a way to allow for this double counting? Thanks in advance. I really appreciate your help.

**Comment by ChristopherWilks** [comment]
Hi @nickhsmith,

I'm not sure if you found help for your last question, but thought I'd chime in here as the author of the original Megadepth which is wrapped by this package in R.

As you thought, Megadepth by default will only count primary alignments, so assuming the aligner that produced your BAM file(s) marks them as such, one of those A vs. Bs will get marked as "BAM_FPRIMARY" and the others will be "BAM_FSECONDARY" using the bit flags from the SAM format https://samtools.github.io/hts-specs/SAMv1.pdf

The relevant line in the Megadepth source is:
https://github.com/ChristopherWilks/megadepth/blob/631c885b34be73365332c8ede33fcc5e62c0ad56/megadepth.cpp#L2653

However, this behavior can be changed, at least in the Megadepth binary itself, as per the documentation: https://github.com/ChristopherWilks/megadepth#bamcram-processing (4 paragraph)

I'm not sure if `--filter-in` and `--filter-out` parameters are exposed in the R package, but I'll defer to @lcolladotor  and/or @dzhang32 for that.

**Comment by dzhang32** [comment]
Thanks for the explanation @ChristopherWilks. 

@nickhsmith `--filter-in` and `--filter-out` were previously not directly included in the R package as named arguments, so I added them to [`megadepth::bam_to_junctions()`](http://research.libd.org/megadepth/reference/bam_to_junctions.html) - you can now modify these parameters as needed.

Alternatively and more broadly, you can specify any flag available to the Megadepth binary using `megadepth::megadepth_shell()`. For example, the below code shows how to use `megadepth::megadepth_shell()` to set the `filter-in` and `filter-out` arguments: 

``` r

library(megadepth)

bam_path <- system.file("tests", "test.bam",
                        package = "megadepth", mustWork = TRUE
)

prefix <- file.path(tempdir(), basename(bam_path))

megadepth::megadepth_shell(bam_path, 
                           prefix = prefix, 
                           `all-junctions` = TRUE, 
                           `filter-in` = 65535,
                           `filter-out` = 260)
#> character(0)

megadepth::read_junction_table(paste0(prefix, ".all_jxs.tsv"))
#> # A tibble: 35 x 7
#>    read_name chr     start     end mapping_strand cigar         unique
#>    <chr>     <chr>   <dbl>   <dbl> <chr>          <chr>          <int>
#>  1 26573693  chr10 4358579 4581019 -              61M222441N11M      0
#>  2 59413733  chr10 8458623 8778558 +              13M319936N59M      0
#>  3 63502504  chr10 8722315 8848720 -              50M126406N22M      1
#>  4 15130473  chr10 8722508 8870679 -              61M148172N11M      1
#>  5 22331161  chr10 8756762 8780518 -              62M23757N10M       1
#>  6 37510913  chr10 8756762 8780518 -              62M23757N10M       1
#>  7 38798461  chr10 8756762 8780518 -              62M23757N10M       1
#>  8 62329988  chr10 8756762 8780518 -              62M23757N10M       1
#>  9 66789502  chr10 8756762 8780518 -              62M23757N10M       1
#> 10 78396176  chr10 8756762 8780518 -              62M23757N10M       1
#> # … with 25 more rows
```

<sup>Created on 2021-05-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ChristopherWilks** [comment]
thanks @dzhang32
